#test1: step1.o
#	gcc -o test1 step1.o
#step1.o:step1.c
#	gcc -Wall -Werror -std=gnu99 -pedantic -c step1.c
#test2: step2.o
#	gcc -o test2 step2.o
#step2.o:step2.c
#	gcc -Wall -Werror -std=gnu99 -pedantic -c step2.c

test3: step3.o
	gcc -o test3 step3.o
step3.o:step3.c
	gcc -Wall -Werror -std=gnu99 -pedantic -c step3.c

