numeric: test.cpp
	g++ -o test -Werror -Wall -pedantic -std=gnu++98 -ggdb3 test.cpp function.cpp  parser.cpp calculator.cpp  definer.cpp  tester.cpp numinter2.cpp  mcinter2.cpp extremer.cpp vector.cpp inter.cpp
