numeric: test.cpp
	g++ -o test -Werror -Wall -pedantic -std=gnu++98 -ggdb3 test.cpp function.h function.cpp parser.h parser.cpp calculator.cpp calculator.h definer.h definer.cpp tester.h tester.cpp numinter.h numinter.cpp
