numerics: main.cpp
	g++ -o numerics -Werror -Wall -pedantic -std=gnu++98 -ggdb3 main.cpp function.cpp  parser.cpp calculator.cpp  definer.cpp  tester.cpp numinter2.cpp  mcinter2.cpp extremer.cpp vector.cpp inter.cpp
